MERGE Core.Suffix AS TARGET
USING (VALUES ( 1, 1, NULL, 'BA'),
              ( 2, 1, NULL, 'BSW'),
              ( 3, 1, NULL, 'CALA'),
              ( 4, 1, NULL, 'CCS-P'),
              ( 5, 1, NULL, 'CDRS'),
              ( 6, 1, NULL, 'CFP'),
              ( 7, 1, NULL, 'CLU'),
              ( 8, 1, NULL, 'CPA'),
              ( 9, 1, NULL, 'CPT'),
              (10, 1, NULL, 'CRR'),
              (11, 1, NULL, 'CSW'),
              (12, 1, NULL, 'DC'),
              (13, 1, NULL, 'DDS'),
              (14, 1, NULL, 'DMD'),
              (15, 1, NULL, 'DO'),
              (16, 1, NULL, 'DPM'),
              (17, 1, NULL, 'EdD'),
              (18, 1, NULL, 'Esq'),
              (19, 1, NULL, 'FACC'),
              (20, 1, NULL, 'II'),
              (21, 1, NULL, 'III'),
              (22, 1, NULL, 'IV'),
              (23, 1, NULL, 'JD'),
              (24, 1, NULL, 'Jr'),
              (25, 1, NULL, 'LCSW'),
              (26, 1, NULL, 'LMSW'),
              (27, 1, NULL, 'LPN'),
              (28, 1, NULL, 'LSW'),
              (29, 1, NULL, 'LVN'),
              (30, 1, NULL, 'MA'),
              (31, 1, NULL, 'MA,MBA'),
              (32, 1, NULL, 'MBA'),
              (33, 1, NULL, 'MD'),
              (34, 1, NULL, 'Med, CPC'),
              (35, 1, NULL, 'MFT'),
              (36, 1, NULL, 'MPA'),
              (37, 1, NULL, 'MPH'),
              (38, 1, NULL, 'MS'),
              (39, 1, NULL, 'MS, OTR/L'),
              (40, 1, NULL, 'MSN'),
              (41, 1, NULL, 'MSW'),
              (42, 1, NULL, 'NHA'),
              (43, 1, NULL, 'OT'),
              (44, 1, NULL, 'OTR'),
              (45, 1, NULL, 'PA'),
              (46, 1, NULL, 'PhD'),
              (47, 1, NULL, 'PLLC'),
              (48, 1, NULL, 'PT'),
              (49, 1, NULL, 'PTA'),
              (50, 1, NULL, 'RDMS'),
              (51, 1, NULL, 'RG'),
              (52, 1, NULL, 'RN'),
              (53, 1, NULL, 'RRT'),
              (54, 1, NULL, 'RT(M)'),
              (55, 1, NULL, 'SpT'),
              (56, 1, NULL, 'Sr'),
              (57, 1, NULL, 'SSD'),
              (58, 1, NULL, 'ST'),
              (59, 1, NULL, 'SW'),
              (60, 1, NULL, 'NP'),
              (61, 1, NULL, 'BSN'),
              (62, 1, NULL, 'ARNP'),
              (63, 1, NULL, 'APRN'))
AS SOURCE (SuffixId,
           RowStatusId,
           SortOrder,
           SuffixValue)
ON TARGET.SuffixId = SOURCE.SuffixId
WHEN MATCHED THEN UPDATE SET TARGET.SuffixValue = SOURCE.SuffixValue,
                             TARGET.SortOrder   = SOURCE.SortOrder,
                             TARGET.RowStatusId = SOURCE.RowStatusId
WHEN NOT MATCHED THEN INSERT (SuffixId,
                              SuffixValue,
                              SortOrder,
                              RowStatusId)
                      VALUES (SOURCE.SuffixId,
                              SOURCE.SuffixValue,
                              SOURCE.SortOrder,
                              SOURCE.RowStatusId)
WHEN NOT MATCHED BY SOURCE THEN DELETE;